# Docker compose file for Observium
# Modified from https://github.com/somsakc/docker-observium

version: '3'

services:
  db:
    image: mariadb:10.6.4
    environment:
      - MYSQL_ROOT_PASSWORD=passw0rd
      - MYSQL_USER=observium
      - MYSQL_PASSWORD=passw0rd
      - MYSQL_DATABASE=observium
      - TZ=America/Halifax
    volumes:
      - ./data:/var/lib/mysql
    networks:
      - clab
    restart: unless-stopped

  app:
    image: martimy/observium:23.9
    privileged: true
    environment:
      - OBSERVIUM_ADMIN_USER=admin
      - OBSERVIUM_ADMIN_PASS=passw0rd
      - OBSERVIUM_DB_HOST=db
      - OBSERVIUM_DB_NAME=observium
      - OBSERVIUM_DB_USER=observium
      - OBSERVIUM_DB_PASS=passw0rd
      - OBSERVIUM_BASE_URL=http://localhost:8888
      - TZ=America/Halifax
    volumes:
      - ./logs:/opt/observium/logs
      - ./rrd:/opt/observium/rrd
    networks:
      clab:
        ipv4_address: 172.20.20.200
    ports:
      - "8888:80"
    restart: unless-stopped
    depends_on:
      - db

networks:
  clab:
      driver: bridge
      external: true
